### ISSUE TITLE
There is out of listen method in Store interface

### ISSUE THREAD

**Issue by sixwinds** [retyped/reflux-tsd-ambient#1]
When writing react class by using es6, mixins can't be used. So store listenser should be written like this:
```javascript
    componentDidMount: function() {
        this.unsubscribe = statusStore.listen(this.onStatusChange);
    },
```
https://github.com/reflux/refluxjs#react-component-example

**Comment by shyiko** [comment]
Hi. Thanks for reporting. If you have a change ready - I'd be happy to merge in a PR.

**Comment by sixwinds** [comment]
Hi Shyiko, I just sent a PR. :)

**Comment by shyiko** [comment]
:+1:
